# **NumPy**
### What is NumPy?

- NumPy (Numerical Python) is a powerful library in Python used for numerical computing. 
- It provides fast, memory-efficient arrays and mathematical functions to handle large datasets.

### Why use NumPy?

- Faster than Python lists (uses C under the hood)
- Memory-efficient (stores data compactly)
- Supports mathematical operations (vectorized operations)
- Can handle large datasets efficiently
- Used in Data Science, Machine Learning, Image Processing, and more

### Real-Life Connection

- Think of NumPy as the "sattu" of data analysis—compact, powerful, and essential for every data meal!



#### How to Install Numpy
Run the following command in your terminal or command prompt:

`pip install numpy`

#### Importing NumPy
Before using NumPy, import it as:

In [2]:
import numpy as np

Why Use `import numpy as np`?
- Saves typing time – Instead of writing numpy.array(), we can just write np.array().
- Follows community standard – Most programmers use np as the convention.
- Improves code readability – Shorter function names make the code cleaner and easier to read.

#### NumPy vs List Performance

- NumPy is significantly faster than lists due to vectorized operations

In [3]:
import time

size = 1000000
list1 = list(range(size))
list2 = list(range(size))

arr1 = np.array(list1)
arr2 = np.array(list2)

# List Addition
start = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
print("List Time:", time.time() - start)

# NumPy Array Addition
start = time.time()
result_array = arr1 + arr2
print("NumPy Time:", time.time() - start)

List Time: 0.08751606941223145
NumPy Time: 0.0


### What is a NumPy Array?
A NumPy array (ndarray) is a fast, memory-efficient way to store and manipulate numerical data. Unlike Python lists, NumPy arrays provide:
- Faster operations (because of vectorization)
- Less memory consumption (compact storage)
- Support for mathematical computations

### **create numpy array**


In [6]:
# 1D array (vector)
arr1 = np.array([1, 2, 3, 4, 5])  
print(arr1) 
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
# 2D array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  
print(arr2)
print(type(arr2))
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [8]:
# 3D array (Tensor)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)
print(type(arr3))
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
(2, 2, 2)


## Array Attributes
- **shape**: Returns a tuple that represents the size of the array along each dimension.
- **size**: Returns the total number of elements in the array
- **ndim**: Returns the number of dimensions (axes) of the array
- **dtypes**: Returns the data type of array elements

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   
print(arr.size)    
print(arr.ndim)   
print(arr.dtype) 

(2, 3)
6
2
int64


#### Special Arrays in NumPy

In [11]:
# array of zeros
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# array of ones
arr = np.ones((2, 3))  
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# array of constants
arr = np.full((2, 3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [14]:
# identity matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# evenly spaced
# using arange function: (Similar to range but returns NumPy array)
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [18]:
# linearly spaced numbers
# using linspace function
arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


### Reshaping Array
**reshape : to change the shape of array**

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape(2, 3)  
print(arr_reshaped)

[[1 2 3]
 [4 5 6]]


#### Accessing Elements in NumPy Arrays
- NumPy uses zero-based indexing (just like Python lists).
- Syntax: `array[row, column]` for 2D arrays.

In [20]:
#1D array
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  
print(arr[2])  
print(arr[-1])

10
30
50


In [21]:
#2D array
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print(matrix[0, 1])  
print(matrix[2, -1])

2
9


#### Slicing Arrays (Extracting Subarrays)
- Syntax: `array[start:stop:step]` (same as Python lists)
- For 2D arrays: `array[row_start:row_stop, col_start:col_stop]`

In [22]:
# 1D array
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4]) 
print(arr[:3])  
print(arr[::2]) 
print(arr[::-1])

[20 30 40]
[10 20 30]
[10 30 50]
[60 50 40 30 20 10]


In [23]:
# 2D array
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print(matrix[0:2, 1:3])  
print(matrix[:, 1])      
print(matrix[1, :])      
print(matrix[::-1, ::-1])


[[2 3]
 [5 6]]
[2 5 8]
[4 5 6]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


#### **Arithmetic Operations on Numpy Array (Element Wise operation)**

In [24]:

a=np.array([12,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a//b)

[16  7  9]
[ 8 -3 -3]
[48 10 18]
[3 0 0]


#### Aggregate Functions
- NumPy provides built-in functions to compute aggregate values.

In [25]:
arr = np.array([10, 20, 30, 40, 50])

print(np.sum(arr))   
print(np.min(arr))   
print(np.max(arr))   
print(np.mean(arr))  
print(np.median(arr))
print(np.std(arr))  

150
10
50
30.0
30.0
14.142135623730951


#### Broadcasting in NumPy
- Broadcasting allows NumPy to perform operations between arrays of different shapes efficiently.

In [26]:
arr = np.array([1, 2, 3, 4])
print(arr + 10)  

[11 12 13 14]


In [27]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

print(matrix + vector)  

[[11 22 33]
 [14 25 36]]


#### matrix operations
- NumPy provides built-in functions for matrix operations.

In [28]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication
print(A @ B)         # Alternative matrix multiplication
print(A.T)           # Transpose of A

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


### **some universal functions in numpy**

In [ ]:
#Square Root
a=np.array([[1,2,3],[1,2,16]])

a=np.sqrt(a)
print(a)

[[1.         1.41421356 1.73205081]
 [1.         1.41421356 4.        ]]


In [ ]:
#Exponencial e^X(E KI POWER ELEMENT OF ARRAY)


a=np.array([1,2,3])

np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
#Logarithmic (e base)
a=np.array([2.71828183,100])
np.log(a)

array([1.        , 4.60517019])

In [ ]:

a=np.array([90,0,30])
radians = np.radians(a)  # Degrees ko Radians me convert karna zaroori hai
# print(radians)

[]
#Sin
sini=np.sin(radians)
print(sini)






[1.  0.  0.5]


In [ ]:
#sum

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

#Collumn Wise
print(np.sum(a))

#Row Wise
print(np.sum(a, axis=1))

21
[ 6 15]


In [ ]:
#Mean
print(np.mean(a))  # Poore array ka mean
print(np.mean(a, axis=0))  # Column-wise mean
print(np.mean(a, axis=1))  # Row-wise mean



3.5
[2.5 3.5 4.5]
[2. 5.]


In [ ]:
#Median
print(np.median(a))  # Poore array ka median
print(np.median(a, axis=0))  # Column-wise median
print(np.median(a, axis=1))  # Row-wise median

3.5
[2.5 3.5 4.5]
[2. 5.]


In [ ]:

#Deviation

print(np.std(a))  # Poore array ka standard deviation
print(np.std(a, axis=0))  # Column-wise std dev
print(np.std(a, axis=1))  # Row-wise std dev

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [ ]:
#variance
print(np.var(a))  # Poore array ka variance
print(np.var(a, axis=0))  # Column-wise variance
print(np.var(a, axis=1))  # Row-wise variance

2.9166666666666665
[2.25 2.25 2.25]
[0.66666667 0.66666667]


#### Sorting an Array

In [29]:
arr = np.array([5, 3, 8, 1, 2])
print(np.sort(arr)) 

[1 2 3 5 8]


In [30]:
# sorting in 2d array
matrix = np.array([[3, 2, 1], [6, 5, 4]])
print(np.sort(matrix, axis=0))  # Column-wise sorting
print(np.sort(matrix, axis=1))  # Row-wise sorting

[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


#### searching for an element

In [31]:
arr = np.array([10, 20, 30, 40, 50])
print(np.where(arr > 25))  # Output: (array([2, 3, 4]),) → Indexes where condition is met


(array([2, 3, 4]),)


## Numpy Practise Questions
- Create a 1D, 2D, and 3D NumPy array.
- Access the first row and last column of a 2D array.
- Perform element-wise addition, subtraction, and multiplication on two arrays.
- Find the sum, mean, min, max, and standard deviation of an array.
- Reshape a 1D array into a 3×3 matrix.
- Sort an array in ascending order.
- Generate a 2×3 matrix of random numbers.
- Find unique elements in an array.
- Multiply two matrices using np.dot().
- Find the inverse of a square matrix.